### ISSUE TITLE
[BUG/ISSUE] RuntimeError when plotting 1-year fullchem benchmark emissions by category

### ISSUE THREAD

**Issue by msulprizio** [geoschem/gcpy#129]
The 1-year full-chemistry benchmark plots are crashing when generating the emission plots. There's a lot of error output from the parallelization (`RuntimeError: main thread is not in main loop`), but it seems to stem from something having to do with the benchmark categories:

```
Traceback (most recent call last):
  File "/n/holyscratch01/jacob_lab/msulprizio/GC/benchmarks/1yr/13.2.0/GCClassic/FullChem/BenchmarkResults/./run_1yr_fullchem_benchmark.py", line 505, in <module>
    bmk.make_benchmark_emis_plots(
  File "/n/home05/msulprizio/python/gcpy/gcpy/benchmark.py", line 1423, in make_benchmark_emis_plots
    results = Parallel(n_jobs=n_job)(delayed(createfile_hco_cat)(c)
```

I still get errors that seem to indicate threading even though I’ve passed n_jobs=1 (and added a print to confirm that was the case). With verbose on, I can see the Aircraft and Anthro HEMCO categories get plotted, but then I encounter an error for Bioburn:

```
...
Adding bookmark for EmisSOAP_Anthro with name SOAP_Anthro
Adding bookmark for EmisTOLU_Anthro with name TOLU_Anthro
Adding bookmark for EmisXYLE_Anthro with name XYLE_Anthro
BioBurn
Exception ignored in: <function Image.__del__ at 0x2ba17b589790>
Traceback (most recent call last):
  File "/n/seasasfs02/msulprizio/python/miniconda/envs/gcpy/lib/python3.9/tkinter/__init__.py", line 4015, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x2ba17b589790>
Traceback (most recent call last):
  File "/n/seasasfs02/msulprizio/python/miniconda/envs/gcpy/lib/python3.9/tkinter/__init__.py", line 4015, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop

...same error over and over...

RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x2ba17b589790>
Traceback (most recent call last):
  File "/n/seasasfs02/msulprizio/python/miniconda/envs/gcpy/lib/python3.9/tkinter/__init__.py", line 4015, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Tcl_AsyncDelete: async handler deleted by the wrong thread
Aborted (core dumped)
```

I believe I was able to address this by downgrading one of the packages in my environment and will follow up with details.

**Comment by lizziel** [comment]
Hi @msulprizio, I did not run into this issue when I ran locally on my machine. When you have a chance could you post the details of the package update you had to make if you still have that info somewhere?

**Comment by msulprizio** [comment]
The solution for this was to downgrade xarray to 0.17.0:

```
     xarray  {0.19.0 (conda-forge/noarch) -> 0.17.0 (conda-forge/noarch)}
```
