### ISSUE TITLE
[BUG/ISSUE] Error when generating GCHP emission plots with 13.4.0

### ISSUE THREAD

**Issue by msulprizio** [geoschem/gcpy#145]
## Describe the bug

When generating benchmark plots for GCHP 13.3.0 vs 13.4.0, I get the following error for the emission plots:

```
%%% Creating GCHP vs. GCHP emissions plots %%%
Traceback (most recent call last):
  File "/n/holyscratch01/jacob_lab/msulprizio/GC/benchmarks/1mon/./run_1mo_benchmark.py", 
line 1371, in <module>
    main()
  File "/n/holyscratch01/jacob_lab/msulprizio/GC/benchmarks/1mon/./run_1mo_benchmark.py", 
line 1367, in main
    run_benchmark(config)
  File "/n/holyscratch01/jacob_lab/msulprizio/GC/benchmarks/1mon/./run_1mo_benchmark.py", 
line 1080, in run_benchmark
    bmk.make_benchmark_emis_plots(
  File "/n/home05/msulprizio/python/gcpy/gcpy/benchmark.py", line 1431, in make_benchmark_emis_plots
    results = Parallel(n_jobs=n_job)(delayed(createfile_hco_cat)(c)
  File "/n/seasasfs02/msulprizio/python/miniconda/envs/gcpy/lib/python3.9/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/n/seasasfs02/msulprizio/python/miniconda/envs/gcpy/lib/python3.9/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/n/seasasfs02/msulprizio/python/miniconda/envs/gcpy/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/n/seasasfs02/msulprizio/python/miniconda/envs/gcpy/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/n/seasasfs02/msulprizio/python/miniconda/envs/gcpy/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
ValueError: cannot rename 'lev' because it is not a variable or dimension in this dataset
real 1115.46
user 6311.88
sys 70.13
srun: error: holy2c12213: task 0: Exited with exit code 1
```

## To Reproduce
I used [1mo_benchmark.yml](https://github.com/geoschem/gcpy/files/8391909/1mo_benchmark.yml.txt) with the latest `dev` branch of GCPy.

## Additional context
@lizziel @LiamBindle Could this be due to the update to flip vertical dimensions of the emissions diagnostics in GCHP? Do we need to modify GCPy for this change?

**Comment by msulprizio** [comment]
Correction: I'm using commit 92799047 in the `dev` branch (i.e. not including the flexible benchmark date feature merged yesterday)

**Comment by msulprizio** [comment]
FYI, I'm getting the same "ValueError: cannot rename 'lev' because it is not a variable or dimension in this dataset" error with GCHP vs. GCHP column AOD plots

**Comment by lizziel** [comment]
The vertical flipping change for emissions isn't until 14.0 so it's not that. (To answer your question about it, yes, GCPy will need to be updated when the change takes effect.) Could you rerun with parallelization off? That should give a better traceback.
