### ISSUE TITLE
[BUG/ISSUE] Error when generating GCHP vs GCClassic diff-of-diff plots with 13.4.0

### ISSUE THREAD

**Issue by msulprizio** [geoschem/gcpy#146]
## Describe the bug

Diff-of-diff plotting gives the following errors when comparing 13.3.0 output to 13.4.0:

```
%%% Creating GCHP vs. GCC diff-of-diffs conc plots %%%

Adding lumped species to ref dataset

Adding lumped species to dev dataset

Archiving lumped_species.yml in /n/holyscratch01/jacob_lab/msulprizio/GC/benchmarks/1mon/G
CHP_13.4.0-rc.3/BenchmarkResults/GCHP_GCC_diff_of_diffs

Archiving benchmark_categories.yml in /n/holyscratch01/jacob_lab/msulprizio/GC/benchmarks/
1mon/GCHP_13.4.0-rc.3/BenchmarkResults/GCHP_GCC_diff_of_diffs
Traceback (most recent call last):
  File "/n/holyscratch01/jacob_lab/msulprizio/GC/benchmarks/1mon/./run_1mo_benchmark.py", 
line 1371, in <module>
    main()
  File "/n/holyscratch01/jacob_lab/msulprizio/GC/benchmarks/1mon/./run_1mo_benchmark.py", 
line 1367, in main
    run_benchmark(config)
  File "/n/holyscratch01/jacob_lab/msulprizio/GC/benchmarks/1mon/./run_1mo_benchmark.py", 
line 1348, in run_benchmark
    bmk.make_benchmark_conc_plots(
  File "/n/home05/msulprizio/python/gcpy/gcpy/benchmark.py", line 1088, in make_benchmark_conc_plots
    results = Parallel(n_jobs=n_job)(
  File "/n/seasasfs02/msulprizio/python/miniconda/envs/gcpy/lib/python3.9/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/n/seasasfs02/msulprizio/python/miniconda/envs/gcpy/lib/python3.9/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/n/seasasfs02/msulprizio/python/miniconda/envs/gcpy/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/n/seasasfs02/msulprizio/python/miniconda/envs/gcpy/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/n/seasasfs02/msulprizio/python/miniconda/envs/gcpy/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
ValueError: operands could not be broadcast together with shapes (1,72,6,24,24) (1,72,6,48,48) 
```

## To Reproduce
I used [1mo_benchmark.yml](https://github.com/geoschem/gcpy/files/8391909/1mo_benchmark.yml.txt) with the latest `dev` branch of GCPy.

## Additional context
This may be related to #145.

**Comment by lizziel** [comment]
It looks like one of the benchmarks was c24 and the other was c48. It's possible the benchmark code assumes GCHP ref and dev are the same resolution. Is there a reason 13.3 and 13.4 use different resolutions for the GCHP 1-month benchmark?

**Comment by lizziel** [comment]
I checked the 13.3 benchmark plots and that used c48. I think we are still using c48 for 1-month benchmarks and will use c24 for 1-year benchmarks.

**Comment by lizziel** [comment]
Actually, I think the problem is definitely the resolution mismatch. I just realized this is diff-of-diff which subtracts one set of output from the other.

**Comment by msulprizio** [comment]
Thanks @lizziel. Good catch. The issue was in fact that the GCHP 1-month benchmarks for 13.4.0 use c24, while 13.3.0 and earlier used c48 resolution. I ran again with c48 output and did not get these errors. For versions beyond GCHP 13.4.0, we will continue to use c24 (via benchmarking on AWS) so this should also not be an issue as long as we are comparing the same GCHP resolution.
