### ISSUE TITLE
[QUESTIONTypeError: an integer is required]

### ISSUE THREAD

**Issue by Qinchuang2019** [geoschem/gcpy#155]
## Type your question below:
There is a problem when  when I run the case:
import xarray as xr
import gcpy.plot as gcplot
import matplotlib.pyplot as plt
ds = xr.open_dataset('GEOSChem.Restart.20190801_0000z.nc4')
#plot surface Ozone over the North Pacific
gcplot.single_panel(ds['SpeciesRst_O3'].isel(lev=0), title='Surface Ozone over the North Pacific', extent=[80, -90, -10, 60])
plt.show()

Traceback (most recent call last):
  File "plot.py", line 11, in <module>
    gcplot.single_panel(slice_500, title='500mb Ozone over the North Pacific', comap = plt.cm.viridis,log_color_scale=True, extent=[80, -90, -10, 60])
  File "/home-yw/users/YW_fuxiao1/anaconda3/envs/GCPY/lib/python3.8/site-packages/gcpy/plot.py", line 2994, in single_panel
    ax.set_extent(extent, crs=proj)
  File "/home-yw/users/YW_fuxiao1/anaconda3/envs/GCPY/lib/python3.8/site-packages/cartopy/mpl/geoaxes.py", line 904, in set_extent
    projected = self.projection.project_geometry(domain_in_crs, crs)
  File "/home-yw/users/YW_fuxiao1/anaconda3/envs/GCPY/lib/python3.8/site-packages/cartopy/crs.py", line 805, in project_geometry
    return getattr(self, method_name)(geometry, src_crs)
  File "/home-yw/users/YW_fuxiao1/anaconda3/envs/GCPY/lib/python3.8/site-packages/cartopy/crs.py", line 811, in _project_line_string
    return cartopy.trace.project_linear(geometry, src_crs, self)
  File "lib/cartopy/trace.pyx", line 628, in cartopy.trace.project_linear
  File "lib/cartopy/trace.pyx", line 100, in cartopy.trace.geos_from_shapely
TypeError: an integer is required

**Comment by yantosca** [comment]
Thanks for writing @Qinchuang2019.  I wonder if there is some kind package conflicts in your Python environment.  When I ran this script on a restart file I got this plot:

![rst](https://user-images.githubusercontent.com/5880296/185410704-524687f3-8b52-4d0c-8000-fad1432c1a92.png)

Here is the list of the Conda environment I used.  You might try updating package versions to match this:

[conda_list.txt](https://github.com/geoschem/gcpy/files/9374338/conda_list.txt)

In particular I'm using: 
```console
dask                      2021.12.0          pyhd8ed1ab_0    conda-forge
dask-core                 2021.12.0          pyhd8ed1ab_0    conda-forge
python                    3.9.7                h12debd9_1    defaults
netcdf-fortran            4.5.4           nompi_h2b6e579_100    conda-forge
matplotlib-base           3.4.2            py39h2fa2bec_0    conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
netcdf4                   1.5.8           nompi_py39h64b754b_101    conda-forge
numpy                     1.21.2           py39hd8d4704_0    defaults
xarray                    0.20.2             pyhd8ed1ab_0    conda-forge
```

**Comment by Qinchuang2019** [comment]
Thank you. You're right. I have reinstalled GCPY. Python =3.9 does not have this problem.
