### ISSUE TITLE
[QUESTION] Creating stretch grid restart files with updated gcpy?

### ISSUE THREAD

**Issue by 1Dandan** [geoschem/gcpy#161]
Hi,
    I am trying to use GCPy to create restart files for stretch grid simulations. I use the container of `docker('geoschem/gcpy:latest')` and command lines of:
```
python -m gcpy.file_regrid                                  \
               -i initial_GEOSChem_rst.c90_fullchem.nc   \
               --dim_format_in checkpoint                     \
               -o sg_restart_c48_3_260_40.nc                  \
               --cs_res_out 48                                \
               --sg_params_out 3.0 260.0 40.0                 \
               --dim_format_out checkpoint
```
It works well previously (probably with older version but I always add latest tag for all my containers and thus do not know what exactly the version is), but I receive errors now as shown below:
```
/gcpy/gcpy/file_regrid.py:8: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(xe.__version__) < LooseVersion("0.2.1"):
Create weight file: ./conservative_sg01f0b92_F0_sg1734f15_F0.nc
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/gcpy/gcpy/file_regrid.py", line 420, in <module>
    file_regrid(
  File "/gcpy/gcpy/file_regrid.py", line 106, in file_regrid
    regridders = make_regridder_S2S(
  File "/gcpy/gcpy/regrid.py", line 229, in make_regridder_S2S
    regridder = xe.Regridder(igrid_list[i_face],
  File "/usr/local/lib/python3.10/site-packages/xesmf/frontend.py", line 235, in __init__
    self._write_weight_file()
  File "/usr/local/lib/python3.10/site-packages/xesmf/frontend.py", line 277, in _write_weight_file
    regrid = esmf_regrid_build(self._grid_in, self._grid_out, self.method,
  File "/usr/local/lib/python3.10/site-packages/xesmf/backend.py", line 277, in esmf_regrid_build
    regrid = ESMF.Regrid(sourcefield, destfield, filename=filename,
  File "/usr/local/lib/python3.10/site-packages/ESMF/util/decorators.py", line 81, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/ESMF/api/regrid.py", line 149, in __init__
    raise ImportError(msg)
ImportError: Regrid(filename) requires PIO and does not work if ESMF has not been built with MPI support
```

I also tried using another container but receive errors indicating it may not create correct restart files:
```
Create weight file: ./conservative_sgd8d7356_F0_sg1734f15_F0.nc
iface 0 doesn't intersect oface 0
Create weight file: ./conservative_sgd8d7356_F1_sg1734f15_F0.nc
iface 1 doesn't intersect oface 0
Create weight file: ./conservative_sgd8d7356_F2_sg1734f15_F0.nc
iface 2 doesn't intersect oface 0
Create weight file: ./conservative_sgd8d7356_F3_sg1734f15_F0.nc
iface 3 doesn't intersect oface 0
Create weight file: ./conservative_sgd8d7356_F4_sg1734f15_F0.nc
Create weight file: ./conservative_sgd8d7356_F5_sg1734f15_F0.nc
iface 5 doesn't intersect oface 0
Create weight file: ./conservative_sgd8d7356_F0_sg1734f15_F1.nc
iface 0 doesn't intersect oface 1
Create weight file: ./conservative_sgd8d7356_F1_sg1734f15_F1.nc
iface 1 doesn't intersect oface 1
Create weight file: ./conservative_sgd8d7356_F2_sg1734f15_F1.nc
Create weight file: ./conservative_sgd8d7356_F3_sg1734f15_F1.nc
Create weight file: ./conservative_sgd8d7356_F4_sg1734f15_F1.nc
Create weight file: ./conservative_sgd8d7356_F5_sg1734f15_F1.nc
iface 5 doesn't intersect oface 1
Create weight file: ./conservative_sgd8d7356_F0_sg1734f15_F2.nc
Create weight file: ./conservative_sgd8d7356_F1_sg1734f15_F2.nc
Create weight file: ./conservative_sgd8d7356_F2_sg1734f15_F2.nc
Create weight file: ./conservative_sgd8d7356_F3_sg1734f15_F2.nc
Create weight file: ./conservative_sgd8d7356_F4_sg1734f15_F2.nc
Create weight file: ./conservative_sgd8d7356_F5_sg1734f15_F2.nc
Create weight file: ./conservative_sgd8d7356_F0_sg1734f15_F3.nc
iface 0 doesn't intersect oface 3
Create weight file: ./conservative_sgd8d7356_F1_sg1734f15_F3.nc
iface 1 doesn't intersect oface 3
Create weight file: ./conservative_sgd8d7356_F2_sg1734f15_F3.nc
Create weight file: ./conservative_sgd8d7356_F3_sg1734f15_F3.nc
iface 3 doesn't intersect oface 3
Create weight file: ./conservative_sgd8d7356_F4_sg1734f15_F3.nc
iface 4 doesn't intersect oface 3
Create weight file: ./conservative_sgd8d7356_F5_sg1734f15_F3.nc
iface 5 doesn't intersect oface 3
Create weight file: ./conservative_sgd8d7356_F0_sg1734f15_F4.nc
Create weight file: ./conservative_sgd8d7356_F1_sg1734f15_F4.nc
iface 1 doesn't intersect oface 4
Create weight file: ./conservative_sgd8d7356_F2_sg1734f15_F4.nc
Create weight file: ./conservative_sgd8d7356_F3_sg1734f15_F4.nc
iface 3 doesn't intersect oface 4
Create weight file: ./conservative_sgd8d7356_F4_sg1734f15_F4.nc
Create weight file: ./conservative_sgd8d7356_F5_sg1734f15_F4.nc
iface 5 doesn't intersect oface 4
Create weight file: ./conservative_sgd8d7356_F0_sg1734f15_F5.nc
iface 0 doesn't intersect oface 5
Create weight file: ./conservative_sgd8d7356_F1_sg1734f15_F5.nc
iface 1 doesn't intersect oface 5
Create weight file: ./conservative_sgd8d7356_F2_sg1734f15_F5.nc
Create weight file: ./conservative_sgd8d7356_F3_sg1734f15_F5.nc
iface 3 doesn't intersect oface 5
Create weight file: ./conservative_sgd8d7356_F4_sg1734f15_F5.nc
Create weight file: ./conservative_sgd8d7356_F5_sg1734f15_F5.nc
iface 5 doesn't intersect oface 5
using dimensions ('Y', 'X') from data variable BXHEIGHT as the horizontal dimensions for this dataset.
/opt/conda/lib/python3.9/site-packages/xesmf/frontend.py:477: FutureWarning: ``output_sizes`` should be given in the ``dask_gufunc_kwargs`` parameter. It will be removed as direct parameter in a future version.
  ds_out = xr.apply_ufunc(
using dimensions ('Y', 'X') from data variable BXHEIGHT as the horizontal dimensions for this dataset.
/opt/conda/lib/python3.9/site-packages/xesmf/frontend.py:477: FutureWarning: ``output_sizes`` should be given in the ``dask_gufunc_kwargs`` parameter. It will be removed as direct parameter in a future version.
  ds_out = xr.apply_ufunc(
using dimensions ('Y', 'X') from data variable BXHEIGHT as the horizontal dimensions for this dataset.
using dimensions ('Y', 'X') from data variable BXHEIGHT as the horizontal dimensions for this dataset.
using dimensions ('Y', 'X') from data variable BXHEIGHT as the horizontal dimensions for this dataset.
/opt/conda/lib/python3.9/site-packages/xesmf/frontend.py:477: FutureWarning: ``output_sizes`` should be given in the ``dask_gufunc_kwargs`` parameter. It will be removed as direct parameter in a future version.
  ds_out = xr.apply_ufunc(
using dimensions ('Y', 'X') from data variable BXHEIGHT as the horizontal dimensions for this dataset.
using dimensions ('Y', 'X') from data variable BXHEIGHT as the horizontal dimensions for this dataset.
using dimensions ('Y', 'X') from data variable BXHEIGHT as the horizontal dimensions for this dataset.
using dimensions ('Y', 'X') from data variable BXHEIGHT as the horizontal dimensions for this dataset.
using dimensions ('Y', 'X') from data variable BXHEIGHT as the horizontal dimensions for this dataset.
using dimensions ('Y', 'X') from data variable BXHEIGHT as the horizontal dimensions for this dataset.
/opt/conda/lib/python3.9/site-packages/xesmf/frontend.py:477: FutureWarning: ``output_sizes`` should be given in the ``dask_gufunc_kwargs`` parameter. It will be removed as direct parameter in a future version.
  ds_out = xr.apply_ufunc(
using dimensions ('Y', 'X') from data variable BXHEIGHT as the horizontal dimensions for this dataset.
/opt/conda/lib/python3.9/site-packages/xesmf/frontend.py:477: FutureWarning: ``output_sizes`` should be given in the ``dask_gufunc_kwargs`` parameter. It will be removed as direct parameter in a future version.
  ds_out = xr.apply_ufunc(
using dimensions ('Y', 'X') from data variable BXHEIGHT as the horizontal dimensions for this dataset.
using dimensions ('Y', 'X') from data variable BXHEIGHT as the horizontal dimensions for this dataset.
using dimensions ('Y', 'X') from data variable BXHEIGHT as the horizontal dimensions for this dataset.
/opt/conda/lib/python3.9/site-packages/xesmf/frontend.py:477: FutureWarning: ``output_sizes`` should be given in the ``dask_gufunc_kwargs`` parameter. It will be removed as direct parameter in a future version.
  ds_out = xr.apply_ufunc(
using dimensions ('Y', 'X') from data variable BXHEIGHT as the horizontal dimensions for this dataset.
Traceback (most recent call last):
  File "/my-projects/GCHP-v13.4.1/rundir-c48-LUO/regrid-c48.py", line 7, in <module>
    file_regrid(fin, fout, dim_format_in, dim_format_out, cs_res_out, sg_params_out=[3.0, 260.0, 40.0])
  File "/opt/conda/lib/python3.9/site-packages/gcpy/file_regrid.py", line 135, in file_regrid
    ds_out=xr.open_mfdataset(oface_files, combine='by_coords', concat_dim='F',engine='netcdf4')
  File "/opt/conda/lib/python3.9/site-packages/xarray/backends/api.py", line 952, in open_mfdataset
    raise ValueError(
ValueError: When combine='by_coords', passing a value for `concat_dim` has no effect. To manually combine along a specific dimension you should instead specify combine='nested' along with a value for `concat_dim`.
```
Could you help me with this problem?

Thanks,
Dandan

**Comment by yantosca** [comment]
Thanks for writing @1Dandan.  I wonder if you might try sparselt for reegridding, as I think we are moving away from xESMF.  https://github.com/liambindle/sparselt

**Comment by yantosca** [comment]
Thanks @1Dandan .  Great!  I'll close out this issue

**Comment by gopikrishnangs44** [comment]
@1Dandan Can you please explain how you solved this issue using gcpy.

**Comment by 1Dandan** [comment]
Pinging @Jourdan-He as she wrote the python function to facilitate regridding restart files with [gridspec](https://github.com/LiamBindle/gridspec) and [sparselt](https://github.com/LiamBindle/sparselt) tools.

**Comment by lizziel** [comment]
Is there a plan to eventually bring the capability of creating stretch grid restart files back into GCPy?

**Comment by gopikrishnangs44** [comment]
@lizziel The file @Jourdan-He mentioned is already there in gcpy, but in the developers version. I think future updates will provide the same in stable version of GCPy.

Thank you for your kind responses
