### ISSUE TITLE
[BUG/ISSUE] GCHP vs GCHP emissions halted with "lev is not in dataset" error

### ISSUE THREAD

**Issue by yantosca** [geoschem/gcpy#169]
While testing the updated benchmarking scripts, I ran into this error in creating the GCHP vs GCHP emissions plots:

```console
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/n/home09/ryantosca/miniconda3/envs/gcpy/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
    r = call_item()
  File "/n/home09/ryantosca/miniconda3/envs/gcpy/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/n/home09/ryantosca/miniconda3/envs/gcpy/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/n/home09/ryantosca/miniconda3/envs/gcpy/lib/python3.9/site-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/n/home09/ryantosca/miniconda3/envs/gcpy/lib/python3.9/site-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/n/home09/ryantosca/python/gcpy/gcpy/benchmark.py", line 1476, in createfile_hco_cat
    compare_single_level(
  File "/n/home09/ryantosca/python/gcpy/gcpy/plot.py", line 858, in compare_single_level
    ds_dev_cmps[i] = regrid_comparison_data(
  File "/n/home09/ryantosca/python/gcpy/gcpy/regrid.py", line 647, in regrid_comparison_data
    new_data = reformat_dims(
  File "/n/home09/ryantosca/python/gcpy/gcpy/regrid.py", line 761, in reformat_dims
    ds = ds.rename(dim_formats[format].get('rename', {}))
  File "/n/home09/ryantosca/miniconda3/envs/gcpy/lib/python3.9/site-packages/xarray/core/dataarray.py", line 1742, in rename
    dataset = self._to_temp_dataset().rename(name_dict)
  File "/n/home09/ryantosca/miniconda3/envs/gcpy/lib/python3.9/site-packages/xarray/core/dataset.py", line 3049, in rename
    raise ValueError(
ValueError: cannot rename 'lev' because it is not a variable or dimension in this dataset
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/n/holyscratch01/jacob_lab/ryantosca/bmk/./run_benchmark.py", line 1435, in <module>
    main()
  File "/n/holyscratch01/jacob_lab/ryantosca/bmk/./run_benchmark.py", line 1431, in main
    choose_benchmark_type(config)
  File "/n/holyscratch01/jacob_lab/ryantosca/bmk/./run_benchmark.py", line 104, in choose_benchmark_type
    run_benchmark_default(config)
  File "/n/holyscratch01/jacob_lab/ryantosca/bmk/./run_benchmark.py", line 1132, in run_benchmark_default
    bmk.make_benchmark_emis_plots(
  File "/n/home09/ryantosca/python/gcpy/gcpy/benchmark.py", line 1503, in make_benchmark_emis_plots
    results = Parallel(n_jobs=n_job)(delayed(createfile_hco_cat)(c)
  File "/n/home09/ryantosca/miniconda3/envs/gcpy/lib/python3.9/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/n/home09/ryantosca/miniconda3/envs/gcpy/lib/python3.9/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/n/home09/ryantosca/miniconda3/envs/gcpy/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/n/home09/ryantosca/miniconda3/envs/gcpy/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/n/home09/ryantosca/miniconda3/envs/gcpy/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
ValueError: cannot rename 'lev' because it is not a variable or dimension in this dataset
```
My python environment is described by this [environment.yml](https://github.com/geoschem/gcpy/blob/feature/gchp_1yr_benchmark_diff_of_diffs/docs/environment_files/environment.yml)

Also I'm working in the `feature/gchp_1yr_benchmark_diff_of_diffs` branch.

I will investigate the issue.  The GCHP vs GCC and GCC vs GCC benchmark plots finished without issue.

Also tagging @lizziel @laestrada

**Comment by laestrada** [comment]
@yantosca looks like the xarray dataset doesnt have the necessary variable name `lev`

**Comment by yantosca** [comment]
Thanks @laestrada.  It may be the Ref version that I am testing with (13.2.0) has some emissions that are different than in the Dev version (14.0.0).  Am retesting with 14.0.0 vs 14.0.0 and it seems that it is OK (so far)

**Comment by yantosca** [comment]
This is due to the difference in resolutions between the Dev and Ref versions, as described here. https://github.com/geoschem/gcpy/issues/145
