### ISSUE TITLE
[BUG/ISSUE] Diff-of-diffs error when comparing two versions with different number of species

### ISSUE THREAD

**Issue by msulprizio** [geoschem/gcpy#62]
When creating diff-of-diff plots for GEOS-Chem 12.7.0 vs GEOS-Chem 12.6.0 GCHP vs GCC, GCPy crashes with the following error:

```
%% Creating GCHP vs. GCC diff-of-diffs concentration plots %%%
Traceback (most recent call last):
  File "/n/seasasfs02/msulprizio/python/miniconda/envs/gcpy/lib/python3.6/site-packages/xarray/core/dataset.py", line 896, in _construct_dataarray
    variable = self._variables[name]
KeyError: 'SpeciesConc_OTHRO2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_1mo_benchmark.py", line 570, in <module>
    gcc_diffs[v].attrs = gcc_dev[v].attrs
  File "/n/seasasfs02/msulprizio/python/miniconda/envs/gcpy/lib/python3.6/site-packages/xarray/core/dataset.py", line 970, in __getitem__
    return self._construct_dataarray(key)
  File "/n/seasasfs02/msulprizio/python/miniconda/envs/gcpy/lib/python3.6/site-packages/xarray/core/dataset.py", line 899, in _construct_dataarray
    self._variables, name, self._level_coords, self.dims)
  File "/n/seasasfs02/msulprizio/python/miniconda/envs/gcpy/lib/python3.6/site-packages/xarray/core/dataset.py", line 74, in _get_virtual_variable
    ref_var = variables[ref_name]
KeyError: 'SpeciesConc_OTHRO2'
```

The issue occurs at the following line in run_1mo_benchmark.py:

```
    # Create a ref file that contains GCC differences
    gcc_ref  = xr.open_dataset(gcc_vs_gcc_refspc, drop_variables=skip_vars)
    gcc_dev  = xr.open_dataset(gcc_vs_gcc_devspc, drop_variables=skip_vars)
    with xr.set_options(keep_attrs=True):
        gcc_diffs = gcc_dev - gcc_ref
        for v in gcc_dev.data_vars.keys():
            # Ensure the gcc_diffs Dataset includes attributes
            gcc_diffs[v].attrs = gcc_dev[v].attrs
    gcc_diffs.to_netcdf(diff_of_diffs_refspc)
```

The issue is caused by the loop over gcc_dev.data_vars.keys(). In the case of 12.7.0 vs 12.6.0 output, gcc_dev contains extra species that are not in 12.6.0 and python crashes because it can't find those species in gcc_ref. 

To resolve this, we should only loop over the common fields between the gcc_dev and gcc_ref datasets when creating the difference files.

**Comment by msulprizio** [comment]
This is now fixed in `dev/0.2.0` in commit https://github.com/geoschem/gcpy/commit/c640a24c7427e87379d698ce99500f202a92fc77.
