### ISSUE TITLE
[FEATURE REQUEST] Add capability to use 47-level vertical grids

### ISSUE THREAD

**Issue by msulprizio** [geoschem/gcpy#70]
The zonal mean plots are set up to handle only 72-level vertical grids. The capability to plot other vertical grids, especially the 47-level grid, should be added. Currently, the following error message is returned:

```
%%% Creating GCC vs. GCC FullChemBenchmark concentration plots %%%
Traceback (most recent call last):
  File "./run_1mo_benchmark.py", line 278, in <module>
    sigdiff_files=gcc_vs_gcc_sigdiff)
  File "/n/home05/msulprizio/GC/python/gcpy/gcpy/benchmark.py", line 2795, in make_benchmark_plots
    weightsdir=weightsdir)
  File "/n/home05/msulprizio/GC/python/gcpy/gcpy/benchmark.py", line 1193, in compare_zonal_mean
    raise ValueError(msg)
ValueError: compare_zonal_mean implemented for 72 or 73 levels only. Other values found in Ref.
```

**Comment by WilliamDowns** [comment]
Support for plotting zonal means of the 47-level vertical grid (and comparison with the 72-level grid) has been added in dev/0.2.0.
